name: sozashop_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  badges: ^2.0.2
  barcode_widget: ^2.0.2
  bloc: ^8.0.2
  collection: ^1.15.0
  connectivity_plus: ^2.2.1
  cupertino_icons: ^1.0.2
  custom_refresh_indicator: ^1.1.1
  date_range_form_field: ^1.0.2
  dio: ^4.0.4
  equatable: ^2.0.3
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_keyboard_visibility: ^5.2.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.2.0
  flutter_secure_storage: ^5.0.2
  flutter_speed_dial: ^5.1.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  http: ^0.13.4
  hydrated_bloc: ^8.0.0
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  lottie: ^1.2.2
  multi_select_flutter: ^4.1.2
  open_document: ^1.0.4
  open_file: ^3.2.1
  path_provider: ^2.0.9
  pdf: ^3.7.3
  pull_to_refresh: ^2.0.0
  scrollable_positioned_list: ^0.2.3
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  textfield_tags: ^2.0.0
  timeline_tile: ^2.0.0
  toggle_list: ^0.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.0.5
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/sozashop-2-small.png
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
    - assets/svgs/
    - assets/i18n/
    - .env
    - .env.production
    - .env.development
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
